import { UserData } from "../modules/rbac/user/types/user";
export const tableNames = [
  "GroupRole",
  "UserRole",
  "UserGroup",
  "BlacklistToken",
  "LoggedInUsers",
  // "GatePassItem",
  // "GatePass",
  // "Item",
  // "Customer",
  "Group",
  "AppFeature",
  "Role",
  "User",
];
import { AppFeature } from "../modules/rbac/Features/types/feature";
export const defaultUser: UserData[] = [
  // {
  //   id: "40cfe759-6fgr-4c9a-bcdf-82b9e1b457fb",
  //   username: "bss@admin",
  //   password: "pass2word",
  //   userRole: [],
  //   userGroup: [],
  // },
  // {
  //   id: "40cfe759-6fgr-4c9a-abcd-82b9e1b457fb",
  //   username: "bss@guest",
  //   password: "pass2word",
  //   userRole: [],
  //   userGroup: [],
  // },
  // {
  //   id: "40cfe759-6fgr-4c9a-abcd-83c8d1b457fb",
  //   username: "bss@account",
  //   password: "pass2word",
  //   userRole: [],
  //   userGroup: [],
  // },
  {
    id: "58c55d6a-910c-46f8-a422-4604bea6cd15",
    username: "admin@panel.com",
    password: "pass4everything",
    userRole: [],
    userGroup: [],
    //   companyUser: [],
  },
];

export const features: AppFeature[] = [
  { name: "login.*", label: "Login" },
  { name: "analytics.*", label: "Analytics" },
  {
    name: "analytics.nav.*",
    label: "Analytics (Nav)",
    parentFeatureId: "analytics.*",
  },
  {
    name: "analytics.read.*",
    label: "Analytics Read",
    parentFeatureId: "analytics.*",
  },
  {
    name: "analytics.graphs.*",
    label: "Analytics Graphs",
    parentFeatureId: "analytics.*",
  },
  { name: "login.app.*", label: "Login App", parentFeatureId: "login.*" },
  { name: "login.admin.*", label: "Login Admin", parentFeatureId: "login.*" },
  { name: "voucher.*", label: "Voucher (Nav)" },
  { name: "voucher.create.*", parentFeatureId: "voucher.*", label: "Create" },
  { name: "voucher.read.*", parentFeatureId: "voucher.*", label: "Read" },
  { name: "voucher.update.*", parentFeatureId: "voucher.*", label: "Update" },
  { name: "voucher.restore.*", parentFeatureId: "voucher.*", label: "Restore" },
  {
    name: "voucher.updatePost.*",
    parentFeatureId: "voucher.*",
    label: "Update Post ",
  },
  { name: "voucher.delete.*", parentFeatureId: "voucher.*", label: "Delete" },
  { name: "voucher.pdf.*", parentFeatureId: "voucher.*", label: "Print" },
  { name: "voucher.post.*", parentFeatureId: "voucher.*", label: "Post" },
  { name: "customer.*", label: "Customer (Nav)" },
  { name: "customer.create.*", parentFeatureId: "customer.*", label: "Create" },
  { name: "customer.read.*", parentFeatureId: "customer.*", label: "Read" },
  { name: "customer.update.*", parentFeatureId: "customer.*", label: "Update" },
  { name: "customer.delete.*", parentFeatureId: "customer.*", label: "Delete" },
  {
    name: "customer.restore.*",
    parentFeatureId: "customer.*",
    label: "Restore",
  },
  { name: "item.*", label: "Item (Nav)" },
  { name: "item.create.*", parentFeatureId: "item.*", label: "Create" },
  { name: "item.read.*", parentFeatureId: "item.*", label: "Read" },
  { name: "item.update.*", parentFeatureId: "item.*", label: "Update" },
  { name: "item.delete.*", parentFeatureId: "item.*", label: "Delete" },
  { name: "item.restore.*", parentFeatureId: "item.*", label: "Restore" },
  { name: "user.*", label: "User (Nav)" },
  { name: "user.create.*", parentFeatureId: "user.*", label: "Create" },
  { name: "user.read.*", parentFeatureId: "user.*", label: "Read" },
  { name: "user.update.*", parentFeatureId: "user.*", label: "Update" },
  { name: "user.delete.*", parentFeatureId: "user.*", label: "Delete" },
  {
    name: "user.logout.*",
    parentFeatureId: "user.*",
    label: "Logout(of all devices)",
  },
  {
    name: "user.changePassword.*",
    parentFeatureId: "user.*",
    label: "Change Password",
  },
  { name: "profile.*", label: "Profile" },
  {
    name: "profile.changePassword.*",
    parentFeatureId: "profile.*",
    label: "Profile Change Password",
  },
  {
    name: "profile.logout.*",
    parentFeatureId: "profile.*",
    label: "Profile Logout",
  },
  {
    name: "profile.logouts.*",
    parentFeatureId: "profile.*",
    label: "Profile Logout(of all devices)",
  },
  { name: "setting.*", label: "Setting (Nav)" },
  { name: "setting.read.*", parentFeatureId: "setting.*", label: "Read" },
  { name: "role.*", label: "Role (Nav)" },
  { name: "role.create.*", parentFeatureId: "role.*", label: "Create" },
  { name: "role.read.*", parentFeatureId: "role.*", label: "Read" },
  { name: "role.update.*", parentFeatureId: "role.*", label: "Update" },
  { name: "role.delete.*", parentFeatureId: "role.*", label: "Delete" },
  { name: "group.*", label: "Group (Nav)" },
  { name: "group.create.*", parentFeatureId: "group.*", label: "Create" },
  { name: "group.read.*", parentFeatureId: "group.*", label: "Read" },
  { name: "group.update.*", parentFeatureId: "group.*", label: "Update" },
  { name: "group.delete.*", parentFeatureId: "group.*", label: "Delete" },
  { name: "featurePermission.*", label: "Feature Permissions" },
  {
    name: "featurePermission.update.*",
    parentFeatureId: "featurePermission.*",
    label: "Update",
  },
  // # { name: "company.*", label: "company (Nav)" },
  // # { name: "company.create.*", parentFeatureId: "company.*", label: "Create" },
  // # { name: "company.read.*", parentFeatureId: "company.*", label: "Read" },
  // # { name: "company.update.*", parentFeatureId: "company.*", label: "Update" },
  // # { name: "company.delete.*", parentFeatureId: "company.*", label: "Delete" },
  // {
  //   name: "profile.changeCompany.*",
  //   parentFeatureId: "profile.*",
  //   label: "Change Company",
  // },
  // # { name: "ledger.*", label: "Ledger (Nav)" },
  // # { name: "ledger.report.*", parentFeatureId: "ledger.*", label: "Report" },
  // # {
  // #   name: "ledger.report.view.*",
  // #   parentFeatureId: "ledger.report.*",
  // #   label: "Report View",
  // # },
  // # {
  // #   name: "ledger.report.pdf.*",
  // #   parentFeatureId: "ledger.report.*",
  // #   label: "Report Print",
  // # },
];
